### ISSUE TITLE
WiFiClientSecure not found

### ISSUE THREAD

**Issue by ferreira1120** [FinianLandes/SpotifyEsp32#12]
When installing through the arduino IDE library manager, an error occurs of not finding WiFiClientSecure library.
Upon investigating, it appears that library got renamed to NetworkClientSecure, since even the link in the readme is broken

**Comment by FinianLandes** [comment]
Thanks for the feedback, will fix this asap new version should be up by tomorrow

**Comment by FinianLandes** [comment]
the issue should be fixed now, it takes around 1h for the release to appear in the arduino IDE, if it stil does not work feel free to create another issue
