### ISSUE TITLE
WiFi was not declared in this scope error

### ISSUE THREAD

**Issue by JustEvanB** [FinianLandes/SpotifyEsp32#14]
Followed this setup on an ESP32-S2:

- Installed SpotifyEsp32.h
- Copy and pasted the code from step two and attempted compiling
- Ran into error: Photo attached
![ESPSpotifyError](https://github.com/user-attachments/assets/5d9854d3-5b66-4c09-b30a-20d506a589a8)

No clue about fix?

**Comment by JustEvanB** [comment]
Seems to be fixed by simply adding "#include <WiFi.h>" to SpotifyEsp32.cpp

**Comment by FinianLandes** [comment]
If noted the issue the source code is also already fixed but wanted to add something else in this patch butt will make the update tomorrow.
