### ISSUE TITLE
Simplify integration into existing projects

### ISSUE THREAD

**Issue by T-vK** [FinianLandes/SpotifyEsp32#4]
Hello and thanks for your great work on this library! :) I would like to use it in [WLED](https://github.com/Aircoookie/WLED/) (another open source project). 

But I'm having a few issues:

1. Fixed Redirect URI. 
    In WLED `http://{IP}/` is already reserved for the Web UI, so it can't be the Redirect URI. It would be nice to be able to specify a custom URL.
2. Can't reuse existing HTTP server/client.
    WLED already has an HTTP server/client. It would make sense to be able to pass those to the SpotifyEsp32 constructor to save resources and avoid running servers on multiple ports.
3. Dependent on Serial
    WLED is usually operated without a serial connection and is configured entirely via Wifi. 
    Thus it would be nice if there was a way to retrieve the Refresh Token and Redirect URI programmatically instead of reading from serial. This way I could store the token across reboots and provide the user with the Redirect URI through the web UI.

What are your thoughts on that? :)

**Comment by FinianLandes** [comment]
1. You can set the port of the webserver as parameter in the constructor so put some port over 8000 that should solve this problem.
2. Will look into that for the next update.
3. Im already working on something like that so that will be included in the next update aswell.
That update will probably be released sometime next week.
Thank you for the feedback

**Comment by T-vK** [comment]
Thanks for the quick reply! That sounds great! :)

One more thing I would like to see, is support for [/get-audio-analysis](https://developer.spotify.com/documentation/web-api/reference/get-audio-analysis). The responses can be like 400kB in size though so it could easily be too much for an ESP. Do you think we could add support for ArduinoJson's [filter](https://arduinojson.org/v7/example/filter/)? That combined with using the response streams instead of strings, would allow us to only use minimal amounts of memory. For example if I just need `meta.timestamp`, `beats` and `bars` from the response, it would be awesome if I could pass a filter like:

``` C++
JsonDocument filter;
filter["meta"]["timestamp"] = true;
filter["beats"] = true;
filter["bars"] = true;

String trackId = "11dFghVXANMlKmJXsNCbNl";

response data = sp.get_audio_analysis(trackId, DeserializationOption::Filter(filter));
```

It seems that currently the String interface is used:
``` C++
DeserializationError deserializeJson(JsonDocument& doc, const String& input);
```
String means that we load the entire response body into memory before parsing it.
Using the Stream interface would allow to parse the response while it is getting received, only storing the required properties in memory. Meaning much lower memory consumption when used with filter.
``` C++
DeserializationError deserializeJson(JsonDocument& doc, Stream& input);
```

**Comment by T-vK** [comment]
I agree. It would probably make sense to allow a filter for all methods and pass it down to `Spotify::RestApi` where it can be passed to `deserializeJson` then. I'll try to implement it and keep you posted. If I success, I'll create a PR.

**Comment by FinianLandes** [comment]
Perfect, otherwise ill try it then, one thing please keep the naming in style, so x_x etc.

**Comment by T-vK** [comment]
Of course! :)

**Comment by FinianLandes** [comment]
"Can't reuse existing HTTP server/client.
WLED already has an HTTP server/client. It would make sense to be able to pass those to the SpotifyEsp32 constructor to save resources and avoid running servers on multiple ports."
currently looking into that, what webserver does WLED use? the one from the WebServer.h lib i use too?
As im not sure how i should handle the closing/the server.handleClient() command

**Comment by T-vK** [comment]
WLED uses [ESPAsyncWebServer](https://github.com/Aircoookie/ESPAsyncWebServer) together with [AsyncJson](https://github.com/Aircoookie/WLED/blob/acf6736afdc579e0bb498b9111e2b8ff7cbaab63/wled00/src/dependencies/json/AsyncJson-v6.h) for receiving requests. 
[Here's an example](https://github.com/Aircoookie/WLED/blob/acf6736afdc579e0bb498b9111e2b8ff7cbaab63/usermods/multi_relay/usermod_multi_relay.h#L246-L302) of how it's used and [here's](https://github.com/Aircoookie/WLED/blob/acf6736afdc579e0bb498b9111e2b8ff7cbaab63/usermods/Artemis_reciever/usermod.cpp#L47-L77C6) another one. The server is globally defined [here](https://github.com/Aircoookie/WLED/blob/acf6736afdc579e0bb498b9111e2b8ff7cbaab63/wled00/wled.h#L692).


I'll check with the people from WLED if there is also a standard/recommended way of how they send HTTP requests as a client.

**Comment by FinianLandes** [comment]
Ok thanks, then ill leave that away for now as i use WebServer and the thing is if you save your tokens the webserver will only be used once and then not again, so its not that big big of a size issue i think.

**Comment by FinianLandes** [comment]
Were you able to get anything done with filters? As i now have released version 1.1 which got some new features on how to login, so i could go on to work on that...

**Comment by T-vK** [comment]
I have tried, but I haven't gotten far. It would probably take me another week or so to get it working. So if you have the time, go for it. I'm sure I'll find something else to contribute down the road. :)

**Comment by FinianLandes** [comment]
No problem, ill try to do it, will dind out how long itll take me to do it :)
